language: cpp

addons:
  apt:
    packages:
      - gfortran
      - cmake

script:
 - mkdir build && cd build && cmake .. && make
 - make install DESTDIR=$PWD && rm -rf ./usr/local/* && rmdir ./usr/local
